package hebernate;
// Generated 2016-6-27 19:09:28 by Hibernate Tools 3.4.0.CR1

/**
 * Albumimageurl generated by hbm2java
 */
public class Albumimageurl implements java.io.Serializable {

	private int albumUrlId;
	private int albumId;
	private String albumImageUrl;
	private Integer albumImageType;
	private String albumImageInfo;

	public Albumimageurl() {
	}

	public Albumimageurl(int albumUrlId, int albumId) {
		this.albumUrlId = albumUrlId;
		this.albumId = albumId;
	}

	public Albumimageurl(int albumUrlId, int albumId, String albumImageUrl, Integer albumImageType,
			String albumImageInfo) {
		this.albumUrlId = albumUrlId;
		this.albumId = albumId;
		this.albumImageUrl = albumImageUrl;
		this.albumImageType = albumImageType;
		this.albumImageInfo = albumImageInfo;
	}

	public int getAlbumUrlId() {
		return this.albumUrlId;
	}

	public void setAlbumUrlId(int albumUrlId) {
		this.albumUrlId = albumUrlId;
	}

	public int getAlbumId() {
		return this.albumId;
	}

	public void setAlbumId(int albumId) {
		this.albumId = albumId;
	}

	public String getAlbumImageUrl() {
		return this.albumImageUrl;
	}

	public void setAlbumImageUrl(String albumImageUrl) {
		this.albumImageUrl = albumImageUrl;
	}

	public Integer getAlbumImageType() {
		return this.albumImageType;
	}

	public void setAlbumImageType(Integer albumImageType) {
		this.albumImageType = albumImageType;
	}

	public String getAlbumImageInfo() {
		return this.albumImageInfo;
	}

	public void setAlbumImageInfo(String albumImageInfo) {
		this.albumImageInfo = albumImageInfo;
	}

}
