package hebernate;
// Generated 2016-6-27 19:09:28 by Hibernate Tools 3.4.0.CR1

/**
 * Albuminfo generated by hbm2java
 */
public class Albuminfo implements java.io.Serializable {

	private int albumId;
	private String albumTitle;
	private String albumInfo;
	private Integer hotIndex;

	public Albuminfo() {
	}

	public Albuminfo(int albumId) {
		this.albumId = albumId;
	}

	public Albuminfo(int albumId, String albumTitle, String albumInfo, Integer hotIndex) {
		this.albumId = albumId;
		this.albumTitle = albumTitle;
		this.albumInfo = albumInfo;
		this.hotIndex = hotIndex;
	}

	public int getAlbumId() {
		return this.albumId;
	}

	public void setAlbumId(int albumId) {
		this.albumId = albumId;
	}

	public String getAlbumTitle() {
		return this.albumTitle;
	}

	public void setAlbumTitle(String albumTitle) {
		this.albumTitle = albumTitle;
	}

	public String getAlbumInfo() {
		return this.albumInfo;
	}

	public void setAlbumInfo(String albumInfo) {
		this.albumInfo = albumInfo;
	}

	public Integer getHotIndex() {
		return this.hotIndex;
	}

	public void setHotIndex(Integer hotIndex) {
		this.hotIndex = hotIndex;
	}

}
