package hebernate;
// Generated 2016-6-27 19:09:28 by Hibernate Tools 3.4.0.CR1

/**
 * Artistimageurl generated by hbm2java
 */
public class Artistimageurl implements java.io.Serializable {

	private String artistUrlId;
	private String artistId;
	private String artistImageUrl;
	private Integer artistImageType;
	private String artistImageInfo;

	public Artistimageurl() {
	}

	public Artistimageurl(String artistUrlId, String artistId) {
		this.artistUrlId = artistUrlId;
		this.artistId = artistId;
	}

	public Artistimageurl(String artistUrlId, String artistId, String artistImageUrl, Integer artistImageType,
			String artistImageInfo) {
		this.artistUrlId = artistUrlId;
		this.artistId = artistId;
		this.artistImageUrl = artistImageUrl;
		this.artistImageType = artistImageType;
		this.artistImageInfo = artistImageInfo;
	}

	public String getArtistUrlId() {
		return this.artistUrlId;
	}

	public void setArtistUrlId(String artistUrlId) {
		this.artistUrlId = artistUrlId;
	}

	public String getArtistId() {
		return this.artistId;
	}

	public void setArtistId(String artistId) {
		this.artistId = artistId;
	}

	public String getArtistImageUrl() {
		return this.artistImageUrl;
	}

	public void setArtistImageUrl(String artistImageUrl) {
		this.artistImageUrl = artistImageUrl;
	}

	public Integer getArtistImageType() {
		return this.artistImageType;
	}

	public void setArtistImageType(Integer artistImageType) {
		this.artistImageType = artistImageType;
	}

	public String getArtistImageInfo() {
		return this.artistImageInfo;
	}

	public void setArtistImageInfo(String artistImageInfo) {
		this.artistImageInfo = artistImageInfo;
	}

}
