package hebernate;
// Generated 2016-6-27 19:09:28 by Hibernate Tools 3.4.0.CR1

/**
 * Artistinfo generated by hbm2java
 */
public class Artistinfo implements java.io.Serializable {

	private String artistId;
	private String artistName;
	private String artistInfo;
	private int hotIndex;

	public Artistinfo() {
	}

	public Artistinfo(String artistId, int hotIndex) {
		this.artistId = artistId;
		this.hotIndex = hotIndex;
	}

	public Artistinfo(String artistId, String artistName, String artistInfo, int hotIndex) {
		this.artistId = artistId;
		this.artistName = artistName;
		this.artistInfo = artistInfo;
		this.hotIndex = hotIndex;
	}

	public String getArtistId() {
		return this.artistId;
	}

	public void setArtistId(String artistId) {
		this.artistId = artistId;
	}

	public String getArtistName() {
		return this.artistName;
	}

	public void setArtistName(String artistName) {
		this.artistName = artistName;
	}

	public String getArtistInfo() {
		return this.artistInfo;
	}

	public void setArtistInfo(String artistInfo) {
		this.artistInfo = artistInfo;
	}

	public int getHotIndex() {
		return this.hotIndex;
	}

	public void setHotIndex(int hotIndex) {
		this.hotIndex = hotIndex;
	}

}
