package hebernate;
// Generated 2016-6-27 19:09:28 by Hibernate Tools 3.4.0.CR1

/**
 * Musicsetimage generated by hbm2java
 */
public class Musicsetimage implements java.io.Serializable {

	private String musicsetImageId;
	private String musicsetId;
	private String musicsetImageUrl;

	public Musicsetimage() {
	}

	public Musicsetimage(String musicsetImageId, String musicsetId, String musicsetImageUrl) {
		this.musicsetImageId = musicsetImageId;
		this.musicsetId = musicsetId;
		this.musicsetImageUrl = musicsetImageUrl;
	}

	public String getMusicsetImageId() {
		return this.musicsetImageId;
	}

	public void setMusicsetImageId(String musicsetImageId) {
		this.musicsetImageId = musicsetImageId;
	}

	public String getMusicsetId() {
		return this.musicsetId;
	}

	public void setMusicsetId(String musicsetId) {
		this.musicsetId = musicsetId;
	}

	public String getMusicsetImageUrl() {
		return this.musicsetImageUrl;
	}

	public void setMusicsetImageUrl(String musicsetImageUrl) {
		this.musicsetImageUrl = musicsetImageUrl;
	}

}
