package hebernate;
// Generated 2016-6-27 19:09:28 by Hibernate Tools 3.4.0.CR1

/**
 * Musicsetcontent generated by hbm2java
 */
public class Musicsetcontent implements java.io.Serializable {

	private String musicId;
	private String musicsetId;

	public Musicsetcontent() {
	}

	public Musicsetcontent(String musicId, String musicsetId) {
		this.musicId = musicId;
		this.musicsetId = musicsetId;
	}

	public String getMusicId() {
		return this.musicId;
	}

	public void setMusicId(String musicId) {
		this.musicId = musicId;
	}

	public String getMusicsetId() {
		return this.musicsetId;
	}

	public void setMusicsetId(String musicsetId) {
		this.musicsetId = musicsetId;
	}

}
