package hebernate;
// Generated 2016-6-27 19:09:28 by Hibernate Tools 3.4.0.CR1

/**
 * Musicsetinfo generated by hbm2java
 */
public class Musicsetinfo implements java.io.Serializable {

	private String musicsetId;
	private String musicsetTitle;
	private String musicsetInfo;
	private String musicsetCollector;
	private int hotIndex;

	public Musicsetinfo() {
	}

	public Musicsetinfo(String musicsetId, String musicsetTitle, int hotIndex) {
		this.musicsetId = musicsetId;
		this.musicsetTitle = musicsetTitle;
		this.hotIndex = hotIndex;
	}

	public Musicsetinfo(String musicsetId, String musicsetTitle, String musicsetInfo, String musicsetCollector,
			int hotIndex) {
		this.musicsetId = musicsetId;
		this.musicsetTitle = musicsetTitle;
		this.musicsetInfo = musicsetInfo;
		this.musicsetCollector = musicsetCollector;
		this.hotIndex = hotIndex;
	}

	public String getMusicsetId() {
		return this.musicsetId;
	}

	public void setMusicsetId(String musicsetId) {
		this.musicsetId = musicsetId;
	}

	public String getMusicsetTitle() {
		return this.musicsetTitle;
	}

	public void setMusicsetTitle(String musicsetTitle) {
		this.musicsetTitle = musicsetTitle;
	}

	public String getMusicsetInfo() {
		return this.musicsetInfo;
	}

	public void setMusicsetInfo(String musicsetInfo) {
		this.musicsetInfo = musicsetInfo;
	}

	public String getMusicsetCollector() {
		return this.musicsetCollector;
	}

	public void setMusicsetCollector(String musicsetCollector) {
		this.musicsetCollector = musicsetCollector;
	}

	public int getHotIndex() {
		return this.hotIndex;
	}

	public void setHotIndex(int hotIndex) {
		this.hotIndex = hotIndex;
	}

}
