package hebernate;
// Generated 2016-6-27 19:09:28 by Hibernate Tools 3.4.0.CR1

/**
 * Recmusicsets generated by hbm2java
 */
public class Recmusicsets implements java.io.Serializable {

	private String recommendId;
	private Integer recommentType;
	private String musicsetId;

	public Recmusicsets() {
	}

	public Recmusicsets(String recommendId, String musicsetId) {
		this.recommendId = recommendId;
		this.musicsetId = musicsetId;
	}

	public Recmusicsets(String recommendId, Integer recommentType, String musicsetId) {
		this.recommendId = recommendId;
		this.recommentType = recommentType;
		this.musicsetId = musicsetId;
	}

	public String getRecommendId() {
		return this.recommendId;
	}

	public void setRecommendId(String recommendId) {
		this.recommendId = recommendId;
	}

	public Integer getRecommentType() {
		return this.recommentType;
	}

	public void setRecommentType(Integer recommentType) {
		this.recommentType = recommentType;
	}

	public String getMusicsetId() {
		return this.musicsetId;
	}

	public void setMusicsetId(String musicsetId) {
		this.musicsetId = musicsetId;
	}

}
